### ISSUE TITLE
Consider adding default "host" header to q-http's read() helper

### ISSUE THREAD

**Issue by asutherland** [kriskowal/q-http#1]
Multi-hosted websites like to get a "host" header in their request.  Node does not add this header by default, and there is a lot more boilerplate required to use q-http's request() helper, so it would be nice for read() to add the header by default.  (And/or, since it takes options, allow it to be opt-in or opt-out.)

**Comment by kriskowal** [comment]
Oh, sorry I missed that. If you get a chance, send me a gist with your typical boilerplate and I'll make sure to streamline the library.

**Comment by kriskowal** [comment]
The changes are ready in git. I'm having difficulty publishing with npm. Can't wait to be able to transition to Lode and not have to deal with that.

**Comment by kriskowal** [comment]
It's in NPM. Please close if you can verify.

**Comment by asutherland** [comment]
It works great!  Thank you very much!
