### ISSUE TITLE
request: Ability to issue requests to unix sockets

### ISSUE THREAD

**Issue by qfox** [kriskowal/q-http#5]
Need to provide socketPath property to `http.request` instead of host+port.
http://nodejs.org/docs/v0.8.11/api/http.html#http_http_request_options_callback
`socketPath: Unix Domain Socket (use one of host:port or socketPath)`

**Comment by kriskowal** [comment]
Can do. Thought I’d already taken care of that.

**Comment by qfox** [comment]
Thanks. ;-)

**Comment by kriskowal** [comment]
I have addressed this issue in Q-IO branches v1 and v2. I do not intend to back-port to q-http, which is deprecated. Thank you for the feedback, and…perhaps your patience on which I have relied too much. I just started using Bee to manage issues, which has made it practical to control my back log.

**Comment by qfox** [comment]
@kriskowal Thanks! ;-)
