### ISSUE TITLE
handle redirect

### ISSUE THREAD

**Issue by ddatsh** [kriskowal/q-http#8]
for handle redirect, I modify 
q-io\http.js
replace
var HTTPS = require("https"); // node
to
var HTTP = require("follow-redirects").http; // node

npm install follow-redirects

**Comment by kriskowal** [comment]
q-http is out of service. It has been consolidated into q-io/http. I recommend filing: Q-IO should expose an HTTP module constructor that accepts the Node.js HTTP module or HTTPS module, or a facsimile thereof, as an argument.
